### ISSUE TITLE
I could not edit my profile

### ISSUE THREAD

**Issue by aylin68** [Muzikie/web-player#169]
### Description
When I try to create a profile, I can see that a profile NFT is generated and my account is charged, but the streamer doesn’t return my profile info. I don’t see any error messages either.

It appears that the Web Player dry-runs the transaction without errors, then uploads it to the streamers which is successful. But the steamer fails to index the NFT later on.

### Dependency
Streamer

### Acceptance criteria
- Users should be able to create a profile if the have sufficient balance
- Users should not be able to create a profile if their balance is insufficient
- Users should see correct error messages if the process fails

**Comment by reyraa** [comment]
Resolved by #197
