### ISSUE TITLE
I could create a collection or audio but I could not see it in my profile page

### ISSUE THREAD

**Issue by aylin68** [Muzikie/web-player#171]
### Description
When I create a collection, I should either see an error message indicating that the process failed, or if succeeded, I should be able to see the collection in my profile page.
Since it takes 1-2 blocks for the NFT to be processed, I should inform the user that the collection/audio will be visible shortly (~10-20 seconds). But after this time, the entity (collection/audio) should be visible and accessible.

### Dependency
This could be an error in the Streamer.

### Acceptance criteria
- I should see the error if the creation process fails
- I should be notified that the created entity will be available for a short tiem (10-20 seconds)
- I should see error messages if any.

**Comment by reyraa** [comment]
Already resolved.
