### ISSUE TITLE
Add collect funds functionality

### ISSUE THREAD

**Issue by aylin68** [Muzikie/web-player#173]
### Description
Users need to be able to see their available funds (revenue) and collect them on demand.

### Dependency
None

### Acceptance criteria
As a user (artists) in my profile page:
- I should see the income I made from my audios
- I should see the total value, and value per audio
- I should be able to click on a button and claim all my income.
- I should be able to see how much network fee I have to pay to claim my income.

**Comment by reyraa** [comment]
Resolved by #212
