### ISSUE TITLE
Retrieve and show album details in the create audio form

### ISSUE THREAD

**Issue by reyraa** [Muzikie/web-player#67]
In the create audio form we have a drop down which displays existing albums of the user. At the moment it only displays the collection IDs.
<img width="1089" alt="Screenshot 2023-01-12 at 15 46 22" src="https://user-images.githubusercontent.com/666685/212097460-ff387bec-f28e-481d-aa41-63d16c16ca5f.png">

Ideally, it should display the following information
- Album image in a 30x30px size (optional)
- Album name
- Album release year
- Number of audios added to it

**Comment by haghighatcs** [comment]
It's done
